version: "3.7"

services: 

    #nginx:
    #    image: nginx
    #    ports:
    #        - "80:80"

    service_1:
        build: ./Service_1
        #container_name: service_1
        #dockerfile: 
        image: davidqatraining/service_1
        ports: 
            - "5000:5000"
        networks: 
            - sfia2_network
        depends_on: 
            - service_4
            - service_2
            - service_3
        deploy:
            replicas: 2
        # env_file:
        #     - ~/.dbenvs
        environment: 
            - SECRET_KEY=${SECRET_KEY}   
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}

# export SECRET_KEY=3a617fb3dde7803d7e4513616c2973ee
# export MYSQL_USER=root
# export MYSQL_PASSWORD=hwg10IAR
# export MYSQL_HOST=34.105.241.68
# export MYSQL_PORT=3306
# export MYSQL_DB_NAME=sfia2db
            
    service_2:
        build: ./Service_2
        #container_name: service_2
        image: davidqatraining/service_2
        #ports:
        networks: 
            - sfia2_network
        deploy:
            replicas: 2    

    service_3:
        build: ./Service_3
        #container_name: service_3
        image: davidqatraining/service_3
        #ports:
        networks: 
            - sfia2_network
        deploy:
            replicas: 2

    service_4:
        build: ./Service_4
        #container_name: service_4
        image: davidqatraining/service_4
        #ports:
        networks: 
            - sfia2_network
        deploy:
            replicas: 2
        #environment: 
        #    - SAMPLE=HELLO
            #- DMCCA=${MYSQL}   #after export MYSQL=168.11.22.33 setting env variable
            
networks:
    sfia2_network:
        #name: sfia2_network
        driver: overlay
    #another_network:
    #    driver: bridge
    